### ISSUE TITLE
Support for UbuntuMATE on Raspberry Pi

### ISSUE THREAD

**Issue by carriba** [kerberos-io/kios#10]
Next to [Raspbian](https://www.raspberrypi.org/downloads/raspbian), support also the installation of [Kerberos.io](https://github.com/kerberos-io) under the [UbuntuMATE](https://ubuntu-mate.org/raspberry-pi) OS for the Raspberry Pi.

**Comment by cedricve** [comment]
Cool @carriba, nice idea! Unfortunately I don't have any time at the moment. If you would have time to give it a shot, I'd love to help you.. Would be a nice addition to our documentation website! Thanks man.
