### ISSUE TITLE
Streaming on port 8889 is not password protected

### ISSUE THREAD

**Issue by svatos** [kerberos-io/kios#11]
Hi, i was wondering if it's possible to **protect the streaming of live view** with a password like the admin dashboard is. It's easy to scan an IP with specific range of ports where 8889 is open and **unprotected** from an entry, especialy **if the IP is exposed** to the internet.

Thanks for any idea!
S.

**Comment by Responseless** [comment]
I also noticed this issue while testing external access and would like to see it resolved.

**Comment by cedricve** [comment]
we're giving priority to hardware encoding now, but we definitely take this one into account. Keep you posted.

**Comment by cedricve** [comment]
fixed in version 2.3.0, KiOS 2.4.0
