### ISSUE TITLE
apt-get / dpkg is not available on kios

### ISSUE THREAD

**Issue by danricho** [kerberos-io/kios#14]
I'm not sure if I'm missing something, but running a dedicated kios instance on raspberry pi 2 means that my scripts can't use anything dependent on installing somthing via apt-get.

**Comment by danricho** [comment]
By the way, I am accessing it via ssh.

**Comment by cedricve** [comment]
Correct, kios is an production image. If you want to install custom packages, you should follow the raspbian installation.

**Comment by danricho** [comment]
ok. Thanks for that.
