### ISSUE TITLE
RaspiCam 1080p mode no longer working on v2

### ISSUE THREAD

**Issue by Responseless** [kerberos-io/kios#15]
After a clean install of v2.4.0 I cannot use the resolution of 1920x1080 any longer with Camera Module v2, I had to scale back to 720p mode. I am running a Pi v3. Is there a list of working resolutions/rates for this setup?

**Comment by cedricve** [comment]
Hmm did't tried that resolution. However recommended resolution is 1280 x 960.

**Comment by Responseless** [comment]
1280 x 960 is working as expected.

**Comment by cedricve** [comment]
@Responseless if you have time to check out which resolution work as expected, let me know ;)

**Comment by Responseless** [comment]
@cedricve haha! If I find any higher resolutions that are working correctly I will post results.
