### ISSUE TITLE
Webhooks throttling

### ISSUE THREAD

**Issue by Responseless** [kerberos-io/kios#16]
I would like to request a feature to manage web hooks sending multiple requests within a set time range of milliseconds.

**Comment by traitors-gate** [comment]
+1 ... when I use webhooks to alert my iPhone using IFTTT, I'm currently getting an alert every second. It would me good to have a webhook timeout setting e.g. Only post one message every X seconds.

**Comment by cedricve** [comment]
Good point guys, let's do this!

**Comment by Stubbs** [comment]
I would prefer to have 1 webhook triggered per event, at the moment my Node-red instance gets DDoS'd whenever Kerberos-io detects movement :-)

Perhaps a call when it detects a new event, and another when the event ends.

**Comment by cedricve** [comment]
Yes, we will add throttling but didn't found the time to implement it. 
Follow up here https://github.com/kerberos-io/machinery/issues/96.
