### ISSUE TITLE
Change /etc/passwd

### ISSUE THREAD

**Issue by nicolas-f** [kerberos-io/kios#2]
Hi,

I want to disable root login and add a custom admin account. However /etc/passwd is on read-only access file system.

How to:
- Disable root ssh login
- add account
- remove or disable ssh login of other installed account (ex: admin)

Thanks

**Comment by cedricve** [comment]
Please check this: https://kerberosio.zendesk.com/hc/en-us/articles/208322325-I-can-t-edit-the-root-partition.

**Comment by nicolas-f** [comment]
It works. However when I disable root, I can't log with admin account.. Have to reset the sd card.
