### ISSUE TITLE
Issue storing login credentials and reverting to wizard setup

### ISSUE THREAD

**Issue by espressobeanies** [kerberos-io/kios#27]
OS: KiOS v2.6.0
Platform: Raspberry Pi 2

Issue: KiOS isn't storing the login credentials generated during an initial wizard setup and is re-prompting the wizard after a set number of minutes. Once the wizard completes a second time, the initial settings reappear.

**Comment by cedricve** [comment]
Weird should be fixed by now. Which browser are you using? Is this a fresh install?

**Comment by espressobeanies** [comment]
Mozilla Firefox and yes it was. 

**Update**

I confirmed same issue via Google Chrome and appears to occur frequently. It could be related to a mounted read-only filesystem. I'll confirm this later.

**Comment by espressobeanies** [comment]
Resolved in v2.6.0 via /data/etc/kios.conf file

**Comment by cedricve** [comment]
hey @espressobeanies, how do you mean resolved with /data/etc/kios.conf?
Can you explain your research?
