### ISSUE TITLE
Raspberry Pi 4B support?

### ISSUE THREAD

**Issue by piyushroshan** [kerberos-io/kios#40]
Is there a plan to support Raspberry pi 4 anytime soon?

**Comment by cedricve** [comment]
Yes it will come with the new release of kerberos.io 3.0

Cédric

**Comment by cedricve** [comment]
Support will be released very soon.

**Comment by cedricve** [comment]
RPi4 support will be released next week.

**Comment by fozter** [comment]
No release yet, any ETA?

**Comment by cedricve** [comment]
1st of jan 🙏

Kind regards,
Verstraeten Cédric

**Comment by cedricve** [comment]
Support for Raspberry Pi is now available in version 2.8.0
