### ISSUE TITLE
Kerberos simply not working 

### ISSUE THREAD

**Issue by armando444rt** [kerberos-io/kios#41]
Hi there, I am having major issues getting Kerberos to simply boot up on my raspberry pi 3 B+ my pi simply spits out "reading configuration file: /data/machinery/config/config.xml" then simply says xml file not found. I previously had Kerberos running on the same Pi a few months ago but decided to get a bigger SD card for the Pi and now this issue simply stops me from doing anything. I flashed the .img file using etcher.

**Comment by cedricve** [comment]
Can you try again with version 2.8.0?
