### ISSUE TITLE
Just can't login

### ISSUE THREAD

**Issue by thearduinoguy** [kerberos-io/kios#43]
I just cant login. Fresh install, tried several different image versions, same result - set up the username and password then the login page will not let me in. Even root/root does not work.

**Comment by cedricve** [comment]
Which browser are you using @thearduinoguy ?

**Comment by thearduinoguy** [comment]
I've tried it on Chrome, Edge and Firefox. Same results. Tried the most recent image and one back from that. Same result.

**Comment by cedricve** [comment]
Can you try with latest version 2.8.0?

**Comment by cedricve** [comment]
@thearduinoguy ?
