### ISSUE TITLE
Installer does not work on version 2.8.0 with WiFi setup RPi3+

### ISSUE THREAD

**Issue by kbabka** [kerberos-io/kios#44]
Etcher installer frozen by downloading 100% and nothing happen.

When chosen wired configuration, its O.K.

**Comment by cedricve** [comment]
Thanks for reporting, is it only when selecting WIFI? Or also with the Static IP?
Which OS are you using?

Cédric

**Comment by kbabka** [comment]
Windows 10, dynamic IP, yes only by WiFi config

**Comment by cedricve** [comment]
Interesting just received another ticket about the same issue. Would you have time to quickly verify if you use the combo (ethernet + static IP)?

Can confirm the downloading works, but once you reach 100%, it stops working.

**Comment by kbabka** [comment]
I tested ethernet + static IP and also installer frozen on 100%.

**Comment by cedricve** [comment]
Thanks the issue is here: https://github.com/kerberos-io/etcher/blob/master/lib/gui/app/modules/image-writer.js#L389.

Will need to have some time to debug, but we will get there. Thank for reporting.

**Comment by cedricve** [comment]
@kbabka we fixed the issue, can you please retry by downloading the installer again, and execute it.

**Comment by kbabka** [comment]
Now installer freezes by "Starting ..." see picture

![image](https://user-images.githubusercontent.com/13314573/71928914-c77efe00-3198-11ea-9b08-aacd86a22cd7.png)

**Comment by cedricve** [comment]
How long did you wait might take some time before the changed are applied during the starting process.

Kind regards,
Verstraeten Cédric

**Comment by kbabka** [comment]
I waited about half an hour, maybe longer.
Regards
Karel

**Comment by kbabka** [comment]
When I use original Etcher and download Kerberos.io image file version 2.8 for RPi3, put it in SD card and then copy the configuration files to the first partition, everything works including WiFi connection

**Comment by cedricve** [comment]
You are right, the build is not correct. Will come back.

**Comment by cedricve** [comment]
@kbabka, fixed and tested myself. Please give me your confirmation as well. Thanks!

**Comment by kbabka** [comment]
Yes, I confirm that the installation is already OK. 
Thanx.
