### ISSUE TITLE
Raspberry Pi Zero W support

### ISSUE THREAD

**Issue by Pilskalns** [kerberos-io/kios#8]
Hi,

Tried Raspberry Zero KiOS image on Zero W but it even doesn't boot or blink any image. When I plug same SD card into regular Zero, it boots and works with USB wi-fi dongle _out of the box_. Also, my Zero W works with other distros.

So, I suppose fault is how SD card is prepared. What are possibilities to get it working on Zero W? :)

**Comment by cedricve** [comment]
Hey @Pilskalns, we're preparing a seperate release to support Raspberry Pi Zero W. It will be available in a few days..

**Comment by matright** [comment]
Hi,
I'm also interested in this, do you have any news ?

Thank you

**Comment by cedricve** [comment]
Hey all,

Can you please try this release: 
https://github.com/cedricve/kios/releases/download/develop/kios-raspberrypi-20170425.img.gz

You can follow the advanced installation https://doc.kerberos.io/2.0/installation/KiOS#advanced

Cédric

**Comment by cspanier** [comment]
Doesn't work for me. I only get the RGBC test image shown when powering up my Pi Zero W. The boot partition does not contain a 'bcm2708-rpi-0-w.dtb' file like e.g. raspbian jessie, which might be the cause.

**Comment by cedricve** [comment]
hey @cmaaser sorry I created a wrong build..  Can you retry with this one.

https://github.com/cedricve/kios/releases/download/develop/kios-raspberrypi-20170425.img.gz

**Comment by cspanier** [comment]
This build doesn't seem to boot either @cedricve . It is stuck again on the colored splash screen.

**Comment by cedricve** [comment]
@cmaaser do you see the bcm2708-rpi-0-w.dtb file in /boot?

**Comment by cspanier** [comment]
@cedricve Yes I do.

**Comment by cspanier** [comment]
When replacing start.elf, fixup.dat and bootcode.bin from the latest raspbian image, which have significantly different file sizes, my pi0w boots up (but prints "Failed to create camera component ...." later on).

**Comment by cedricve** [comment]
Great.. well that's because you didn't connect a raspberry pi camera. Can you access the web interface? I'm just reviewing the build process and it looks like I didn't upgraded the userland and firmware libraries. Cross-compiling right now. Thanks for helping!

**Comment by cspanier** [comment]
Actually I do have a camera connected, but it is a new one which I haven't tested before on one of my other regular PIs due to lack of time. I'll test the camera and web interface tomorrow.

**Comment by cedricve** [comment]
Could also be because of the userland library. I'll drop a new build in this topic in a few minutes.

**Comment by cedricve** [comment]
@cmaaser updated the image again, let me know if you had time to check it out. 
https://github.com/cedricve/kios/releases/download/develop/kios-raspberrypi-20170425.img.gz

bootcode.bin is now 50kb instead of 10kb

**Comment by vincenzocostagliola** [comment]
Hi @cedricve , 
the latest image seems working. 
I'm working with the RPI camera and kerberos cloud at moment.
Let me know if you need more info.

**Comment by cedricve** [comment]
@vincenzocostagliola did you tried the image I've commented above? Can you confirm the RPI camera is also working?

**Comment by vincenzocostagliola** [comment]
@cedricve Yes I've tried the image that you posted 3 hours ago.
Yes the RPI Camera ( Rev 1.3 Model) is working.

**Comment by cedricve** [comment]
Ok perfect! let's wait for @cmaaser second approval, as he's using the newever RPI camera.

**Comment by vincenzocostagliola** [comment]
@cedricve I've just tried the v2 Pi NoIR on another PI Zero W and it's working flawlessly.

**Comment by cedricve** [comment]
Awesomeness @vincenzocostagliola ! Ok let's release this. I'll update the docs and created a new release. Can you also verify everything works as expected (e.g. the web interface and all it's pages). I just ordered a Pi Zero W yesterday.

**Comment by vincenzocostagliola** [comment]
@cedricve Seems everything is fine. I've configured the motion and the cloud with no problem. System page also works as expected.

**Comment by cspanier** [comment]
I can confirm that the latest image works flawlessly including camera (V2.1), web access and wifi. Thanks @cedricve !

**Comment by cedricve** [comment]
Awesome guys, let's release the beast. Thank you all for testing and helping.

**Comment by cedricve** [comment]
Released https://github.com/kerberos-io/kios/releases/tag/v2.3.0

**Comment by paulbakker** [comment]
There are 3 images in the releases (kios-raspberrypi-20170425.img.gz, 98.6 MBkios-raspberrypi2-20170425.img.gz, 98.6 MBkios-raspberrypi3-20170425.img.gz). Which one is the correct one for the pi zero?

**Comment by cedricve** [comment]
@paulbakker kios-raspberrypi-20170425.img.gz is the correct one.
